#!/usr/bin/bash
CPPFILE="$1"
if [[ -z "${CPPFILE}" ]]; then
    echo !Usage: $0 CPPFILENAME 1>&2
    exit 1
fi

if ! [ -f "$CPPFILE" ]; then
    echo !No $CPPFILE file in the current directory. 1>&2
    exit 1
fi

SCRIPT_DIR=$( pushd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd && popd &> /dev/null)
MICROLIBS_DIR=`realpath -q "$SCRIPT_DIR/../../microlibs"`

STDCPP="-std=c++17 -pedantic-errors -Wall -Wextra"
g++ $STDCPP -s -I"$MICROLIBS_DIR" -D FMT_HEADER_ONLY "$CPPFILE" cppm.cpp -oa

